### ISSUE TITLE
Registered class League\OAuth2\Client\Provider\GenericProvider does not exist or is not an implementation of League\OAuth2\Client\Provider\AbstractProvider

### ISSUE THREAD

**Issue by frankatjob** [waldhacker/ext-oauth2-client#14]
Get this error when i install oauth2_client from typo3 TER
Registered class League\OAuth2\Client\Provider\GenericProvider does not exist or is not an implementation of League\OAuth2\Client\Provider\AbstractProvider | InvalidArgumentException thrown in file /var/www/html/reservation.cyber.gouv.qc.ca/typo3conf/ext/oauth2_client/Classes/Domain/Model/ProviderConfiguration.php in line 49

TYPO3 [11.5.19]

**Comment by maikschneider** [comment]
Hey, this extensions [requires](https://github.com/waldhacker/ext-oauth2-client/blob/develop/composer.json#L22) the package "league/oauth2-client" which would be automatically installed in a composer-based TYPO3 installation. Since you installed the extension via Extension Manager (or zip-Download), the dependencies are not installed.

Unfortunately this extension does not bundle and ship its dependencies as .har-files. This means, that this extension won't work for you.

**Comment by waldhacker1** [comment]
@maikschneider This is not quite correct.
[In the build process](https://github.com/waldhacker/ext-oauth2-client/blob/01ad0ebf181816157540dbcbb380814d17adea62/build/build-extension.sh#L11) of the TER variant of the extension the external dependencies [are stored under "Resources/Private/PHP/"](https://github.com/waldhacker/ext-oauth2-client/blob/01ad0ebf181816157540dbcbb380814d17adea62/build/release/composer.json#L39) so that they can also be used in non-composer installations.
However, these dependencies were loaded too late, which led to the described errors.
This has now been fixed with version 2.0.2.
At the moment it is not possible to release into TER, but as soon as this is possible again, the extension can be used in non-composer TYPO3 installations.
