### ISSUE TITLE
TYPO3 12 LTS support

### ISSUE THREAD

**Issue by sirdiego** [waldhacker/ext-oauth2-client#19]
Hi guys,

are you working on or have any plans for TYPO3 12 LTS support?

**Comment by FBuchholz** [comment]
Hi guys,

are you working on or have any plans for TYPO3 12 LTS support? We also ask for this.

**Comment by weisgerberm** [comment]
great extension. Any updates for V12 support?

**Comment by maikschneider** [comment]
There is a v12-branch, however it still needs some adjustments. I made it running, however it should not be used in production yet. 

See [PR for the v12-branch](https://github.com/waldhacker/ext-oauth2-client/pull/23)

**Comment by parzerphilipp** [comment]
Fork from @maikschneider works.
@waldhacker1 any new updates for V12 support?

**Comment by Loeffeldude** [comment]
Hey any update on this? What still needs to be done on @maikschneider's fork? Is it ok to use?

**Comment by vertexvaar** [comment]
Hello people,

sadly, there hasn't been any update for a long time. Since we at @in2code-de are using this extension and do require it for TYPO3 and will require it for TYPO3 v13, i've decided to fork and update it. You can find the fork here: https://github.com/in2code-de/ext-oauth2-client and also on packagist: https://packagist.org/packages/in2code/typo3-oauth2-client-fork

Feel free to use our fork. I will maintain it as closely to the original repo as possible.

@waldhacker1 I know maintaining FOSS projects is a thankless job. It requires time, motivation and other resources. Feel free to reach out to me if you would like to have someone assisting you.

**Comment by waldhacker1** [comment]
Hi @vertexvaar 
Thank you for driving the development forward!
In fact, I don't have time to develop the extension at the moment.
Are you (or @in2code-de) interested in becoming the successor of this extension?

**Comment by vertexvaar** [comment]
@waldhacker1

I thought long and hard about whether I wanted to take over the package personally or whether it would be better off with in2code. I decided that it would make the most sense for me to add it to my organization @co-stack (most of them are on gitlab), since I already work on several TYPO3 and other PHP packages there. 

Let's talk in person, in TYPO3 Slack or something, about the details.

**Comment by waldhacker1** [comment]
The Issue has been moved to [GitLab](https://gitlab.com/co-stack.com/co-stack.com/typo3-extensions/typo3-oauth2-client/-/issues/19).
